name = "crypto-recs"
main = "src/worker.ts"
compatibility_date = "2025-08-01"


[triggers]
crons = ["*/1 * * * *"] # co minutę


[vars]
SYMBOLS = "BTCUSDT,ETHUSDT,SOLUSDT"
DEPTH_LIMIT = "100"
LIQ_BIN_SIZE = "50"
USE_MIRROR_ONLY = "1"

[[d1_databases]]
binding = "DB"
database_name = "crypto_recs"
database_id = "5b3dfcfb-de53-4288-b92f-a4de250fa24d"


[observability.logs]
enabled = true

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

